CREATE TABLE [dbo].[Prices]
(
	[ProductID] VARCHAR(50) UNIQUE PRIMARY KEY NOT NULL,
	[SKU] VARCHAR(50) UNIQUE NOT NULL,
	[DiscountNetPrice] DECIMAL(10,2) NULL,
	[LogisticDiscountNetPrice] DECIMAL(10,2) NULL
);